READ_PRIVATE_TOKEN:
  targets:
    - thepwagner-org/private
  permissions:
    metadata: read
    contents: read

PARANOID_GITHUB_TOKEN:
  targets:
    - thepwagner-org/consumer
  permissions:
    metadata: read
    contents: read
