ORG_READ_PRIVATE_TOKEN:
  targets:
    - thepwagner-org/private
    - thepwagner-org/consumer
  permissions:
    contents: read
    issues: read

ORG_WRITE_PRIVATE_TOKEN:
  targets:
    - thepwagner-org/private
  permissions:
    contents: write
  consumers:
    - thepwagner-org/consumer
