ORG_WRITE_PRIVATE_TOKEN:
  targets:
    - thepwagner-org/private
  permissions:
    contents: write

ORG_READ_PRIVATE_TOKEN:
  targets:
    - thepwagner-org/private
  permissions:
    contents: read
    issues: read
  consumers:
    - thepwagner-org/consumer
