name: Synchronize secrets
on:
  workflow_dispatch:
  pull_request:
    types: [reopened]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - uses: ./
        with:
          app_id: ${{ secrets.SG_APP_ID }}
          app_private_key: ${{ secrets.SG_APP_PK }}
          installation_id: ${{ secrets.SG_INSTALL_ID }}
          log_level: debug
